import { useState, useEffect } from 'react';
import { Info, X, ChevronRight } from 'lucide-react';
import { authApi } from '../../lib/api';

export type AIFeatureKey =
  | 'ats_scoring'
  | 'message_generation'
  | 'ai_coach'
  | 'skills_gap'
  | 'linkedin_optimizer'
  | 'resume_generation'
  | 'recruiter_research'
  | 'career_readiness';

interface AIDisclosureBannerProps {
  featureKey: AIFeatureKey;
  onLearnMore?: () => void;
}

const FEATURE_DESCRIPTIONS: Record<
  AIFeatureKey,
  { title: string; description: string; howItWorks: string }
> = {
  ats_scoring: {
    title: 'ATS Compatibility Score',
    description:
      "This score was generated using Jobezie's algorithms analyzing keyword matching, formatting, and achievement quality.",
    howItWorks:
      'Your resume is scored across 7 components: compatibility (15%), keywords (15%), achievements (25%), formatting (15%), progression (15%), completeness (10%), and job fit (5%). Scores are calculated by deterministic algorithms — no AI generates the score itself.',
  },
  message_generation: {
    title: 'AI-Generated Message',
    description:
      "This message was drafted by AI based on your profile and the recruiter's background.",
    howItWorks:
      "Messages are generated using AI (Claude by Anthropic) with context from your resume, target role, and the recruiter's industry. Message quality is scored algorithmically for length (<150 words), personalization, metrics, and call-to-action.",
  },
  ai_coach: {
    title: 'AI Career Coach',
    description:
      'Responses are generated by AI using your career profile for context.',
    howItWorks:
      'The AI Coach uses Claude (Anthropic) with your career stage, skills, target roles, and conversation history to provide personalized guidance. Recommendations are suggestions, not employment decisions.',
  },
  skills_gap: {
    title: 'Skills Gap Analysis',
    description:
      'This analysis uses AI and labor market data to identify skill gaps for your target roles.',
    howItWorks:
      'Your skills are matched against O*NET occupational requirements using semantic similarity (ML) and pattern matching. Gap severity is scored algorithmically. Recommendations are generated by AI.',
  },
  linkedin_optimizer: {
    title: 'LinkedIn Optimization',
    description:
      'These suggestions were generated by AI to improve your LinkedIn profile visibility.',
    howItWorks:
      'Your LinkedIn profile is analyzed against Boolean search patterns recruiters use. Keyword recommendations come from O*NET skill taxonomies. Optimization suggestions are AI-generated.',
  },
  resume_generation: {
    title: 'AI-Generated Resume Content',
    description:
      'This content was created by AI based on your experience and target role.',
    howItWorks:
      'Resume bullets and summaries are generated using AI (Claude/OpenAI) with your work history as context. All generated content should be reviewed and edited to ensure accuracy.',
  },
  recruiter_research: {
    title: 'AI Recruiter Research',
    description:
      'This research summary was generated by AI based on publicly available information.',
    howItWorks:
      'AI synthesizes publicly available information about the recruiter and their company to help you personalize outreach. Always verify facts before using in messages.',
  },
  career_readiness: {
    title: 'Career Readiness Score',
    description:
      "This score was calculated by Jobezie's algorithms based on your profile completeness and activity.",
    howItWorks:
      'Readiness is scored across 5 components: profile completeness (20%), resume quality (25%), network strength (20%), activity level (15%), and response rates (20%). All scores are deterministic algorithms.',
  },
};

function getDismissedFeatures(): Set<AIFeatureKey> {
  try {
    const stored = localStorage.getItem('jobezie_ai_disclosures_dismissed');
    return stored ? new Set(JSON.parse(stored)) : new Set();
  } catch {
    return new Set();
  }
}

function persistDismissal(key: AIFeatureKey): void {
  const dismissed = getDismissedFeatures();
  dismissed.add(key);
  const arr = [...dismissed];
  localStorage.setItem('jobezie_ai_disclosures_dismissed', JSON.stringify(arr));

  // Sync to backend (fire-and-forget)
  authApi.updateProfile({ ai_disclosures_dismissed: arr }).catch(() => {});
}

/**
 * Full dismissible banner — shown on first use of each AI feature.
 * After the user dismisses it, only the persistent AIInfoIcon remains visible.
 */
export function AIDisclosureBanner({ featureKey, onLearnMore }: AIDisclosureBannerProps) {
  const [isDismissed, setIsDismissed] = useState(true);
  const [showDetails, setShowDetails] = useState(false);

  useEffect(() => {
    setIsDismissed(getDismissedFeatures().has(featureKey));
  }, [featureKey]);

  if (isDismissed) return null;

  const feature = FEATURE_DESCRIPTIONS[featureKey];

  const dismiss = () => {
    persistDismissal(featureKey);
    setIsDismissed(true);
  };

  return (
    <div className="rounded-lg border border-blue-200 bg-blue-50 p-4 mb-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100">
            <Info className="h-4 w-4 text-blue-600" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-medium text-blue-900">
              AI-Powered Feature
            </p>
            <p className="mt-1 text-sm text-blue-700">
              {feature.description}
            </p>

            {showDetails && (
              <div className="mt-3 rounded-md bg-white p-3 text-sm text-gray-700 border border-blue-100">
                <p className="font-medium text-gray-900 mb-1">
                  How {feature.title} Works
                </p>
                <p>{feature.howItWorks}</p>
              </div>
            )}
          </div>
        </div>

        <button
          onClick={dismiss}
          className="shrink-0 rounded-md p-1 text-blue-400 hover:bg-blue-100 hover:text-blue-600 transition-colors"
          aria-label="Dismiss AI disclosure"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      <div className="mt-3 flex items-center gap-4 ml-11">
        <button
          onClick={dismiss}
          className="text-sm font-medium text-blue-600 hover:text-blue-800 transition-colors"
        >
          Got it
        </button>
        <button
          onClick={() => {
            setShowDetails(!showDetails);
            if (!showDetails && onLearnMore) onLearnMore();
          }}
          className="flex items-center gap-1 text-sm text-blue-500 hover:text-blue-700 transition-colors"
        >
          {showDetails ? 'Hide details' : 'How it works'}
          <ChevronRight
            className={`h-3 w-3 transition-transform duration-200 ${showDetails ? 'rotate-90' : ''}`}
          />
        </button>
      </div>
    </div>
  );
}

/**
 * Persistent info icon — always visible on AI-generated content.
 * Expands to a tooltip explaining how the feature works.
 */
export function AIInfoIcon({ featureKey }: { featureKey: AIFeatureKey }) {
  const [isOpen, setIsOpen] = useState(false);
  const feature = FEATURE_DESCRIPTIONS[featureKey];

  return (
    <div className="relative inline-block">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="inline-flex items-center gap-1 text-xs text-gray-400 hover:text-blue-500 transition-colors"
        aria-label={`Learn how ${feature.title} works`}
        title="AI-powered feature"
      >
        <Info className="h-3.5 w-3.5" />
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute bottom-full left-0 z-50 mb-2 w-72 rounded-lg border border-gray-200 bg-white p-3 shadow-lg">
            <p className="text-xs font-medium text-gray-900 mb-1">
              {feature.title}
            </p>
            <p className="text-xs text-gray-600">
              {feature.howItWorks}
            </p>
            <p className="mt-2 text-xs text-gray-400 italic">
              AI-generated content is guidance, not employment decisions.
            </p>
          </div>
        </>
      )}
    </div>
  );
}

export { FEATURE_DESCRIPTIONS };
